CREATE TABLE `backtest_jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`jobId` varchar(64) NOT NULL,
	`strategyKey` varchar(100) NOT NULL,
	`strategyName` varchar(200),
	`symbol` varchar(40) NOT NULL,
	`timeframe` varchar(10) NOT NULL,
	`exchange` varchar(20) NOT NULL DEFAULT 'okx',
	`startDate` bigint NOT NULL,
	`endDate` bigint NOT NULL,
	`initialCapital` decimal(20,2) NOT NULL,
	`tradeAmount` decimal(20,2),
	`config` json NOT NULL,
	`status` enum('pending','running','completed','failed','timeout','cancelled') NOT NULL DEFAULT 'pending',
	`progress` int NOT NULL DEFAULT 0,
	`message` text,
	`metrics` json,
	`tradesData` json,
	`equityCurve` json,
	`summary` text,
	`error` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`startedAt` timestamp,
	`completedAt` timestamp,
	CONSTRAINT `backtest_jobs_id` PRIMARY KEY(`id`),
	CONSTRAINT `backtest_jobs_jobId_unique` UNIQUE(`jobId`)
);
